# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1612edd5ff50b10efdafbdb961aeea2d59242c3f396935ee87153a251cbfd6a46510bd88e7944a3c648256c6861692a113a106c48bdaa0b5fed20bee3f15cbc8

test:
  secret_key_base: 9555cb696583fac1a1ea821b76bb7c01fd3821de22810f139cea0678ac38b6d3052b3103ff5c650978f8daf6ad523f68c5488e26c99e0bd497a698547b2f63fa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
